# carbon-metric essentials (resolved to basic values)
prefix p:<http://datacommonsscotland.org/linked-data/property/>
select ?material ?multiplier
where {
	?uri p:hasMaterial ?material;
       p:hasMultiplier ?multiplier.
}


# enablers essentials (resolved to basic values)
prefix rdfs:<http://www.w3.org/2000/01/rdf-schema#>
prefix p:<http://datacommonsscotland.org/linked-data/property/>
select ?name ?latitude ?longitude
where {
	?uri rdfs:label ?name;
       p:hasLatitude ?latitude;
       p:hasLongitude ?longitude.
}


# carbon-savings essentials (resolved to basic values)
prefix p:<http://datacommonsscotland.org/linked-data/property/>
select ?occurrenceDate ?material ?tonnesWeight ?enabler ?enablerSpecific
where {
	?uri p:hasOccurrenceDate ?occurrenceDate;
       p:hasMaterial ?material;
       p:hasTonnesWeight ?tonnesWeight;
       p:hasEnabler ?enabler;
       p:hasEnablerSpecific ?enablerSpecific.
}
