= Having a look at the data about waste on statistics.gov.scot

My https://github.com/data-commons-scotland/dcs-shorts/tree/master/linking-sepa-nrs-data-early-experiment/[previous report]
showed how the Household Waste dataset from SEPA
and the Population dataset from NRS,
could be copied, parsed, consolidated into linked data
(using a local triplestore),
and then queried for information that could form the basis on a couple of infographics.



Since then, I’ve been looking at the http://statistics.gov.scot/[statistics.gov.scot] site.
This site makes many useful datasets available as linked open data.
This includes the datasets from SEPA and NRS that I used last week.
So, in theory, we ought to be able to achieve the same result as we did last week
but with significantly fewer steps since statistic.gov.scot has done that work already.



The detail of putting that theory to the test can be found in
https://nbviewer.jupyter.org/github/data-commons-scotland/dcs-shorts/blob/master/stats-gov-scot-waste-data-investigation/fetch-using-sparql.ipynb[this lab notebook].
It concludes:

* I'm impressed at statistics.gov.scot's platform…
** It manages to curate, link and make accessible a sizeable number of datasets from several sources.
** Its datasets include some (e.g. 
https://statistics.gov.scot/data/household-waste[Household Waste] 
and https://statistics.gov.scot/data/population-estimates-current-geographic-boundaries[Population])
that are core to providing data about waste in Scotland.
* Its SPARQL interface is powerful and has shown itself to be useful.
** However, some care must be taken to ensure that queries against it, are performant.
** For example, we might have to split one query (requiring many _joins_) into
several smaller queries (requiring less _joins_) that are kneading together outside of SPARQL.
* For the general public, statistics.gov.scot is not "easy to use"…
** I have seen several references to this in Slack workspaces (OpenDataScotland and SODU).
** Whereas, statisticians/coders may accept that it is reasonably simple
given that it is kneading together diverse datasets into a coherent knowledge.
** (Certainly it has taken me over one work-day to understand enough about the
structures within statistics.gov.scot, just to be able to construct the queries above.)
** One of the objectives of the Data Commons Scotland project is to
address the "ease of use" issue over open data.