= The geography of household waste generation


Working on his human geography homework, Rory asks:

> Which areas in Scotland are reducing their household waste?"


Looking at the chart which visualises waste amounts against geographic areas, Niamh thinks:

> I wonder why urban populations _seem_ to generated less waste than rural ones?


In a step towards supporting the above scenarios,
this experiment generates https://en.wikipedia.org/wiki/Choropleth_map[choropleth]s to help visualise
the variations in the amounts of household-generated waste across geographic areas in Scotland.

The link:cube-to-chart.ipynb[cube-to-chart] executable notebook
steps through the nitty-gritty of this experiment. The steps include:

1. Running a https://www.w3.org/TR/sparql11-query/[SPARQL]
query against http://statistics.gov.scot/[statistics.gov.scot]'s
very useful https://en.wikipedia.org/wiki/Data_cube[data cube]s
to find the waste tonnage generated per council citizen per year.
1. For each council area, derive the 3 values:
* `recent` - 2018's tonnage of waste generated per council citizen.
* `average` - 2011-2018's average tonnage of waste generated per council citizen.
 (Calculated as the _mean_.)
* `trend` - 2011-2018's trend in tonnage of waste generated per council citizen.
 (Calculated as the gradient of a linear approximation to the tonnage over the years.
 A statistician might well suggest a more appropriate method for computing this _trend_ value.)
1.  Use https://vega.github.io/vega/[Vega]
to generate 3 choropleths which help visualise the statistically values from the above step,
against the council-oriented geography of Scotland.
(The geography data comes from https://github.com/martinjc/UK-GeoJSON[Martin Chorely's good curation work].)

The resulting choropleths can be viewed on the page https://data-commons-scotland/choropleth-generation/choropleths.html[choropleths.html].
